language: minimal
services:
  - docker
matrix:
  include:
  - env: SUBDOMAIN_DIR=www
before_install:
- cd ./$SUBDOMAIN_DIR
script: make build
deploy:
  provider: script
  script: make deploy
  on:
    branch: master
    condition: $TRAVIS_PULL_REQUEST == "false"
  skip_cleanup: true
