language: minimal
services:
  - docker
matrix:
  include:
  - env: SUBDOMAIN_DIR=www
before_install:
- cd ./$SUBDOMAIN_DIR
script: make
deploy:
  provider: script
  script: docker run --rm -e AWS_ACCESS_KEY=$AWS_ACCESS_KEY -e AWS_SECRET_KEY=$AWS_SECRET_KEY $SUBDOMAIN_DIR
  on:
    branch: master
    condition: $TRAVIS_PULL_REQUEST == "false"
  skip_cleanup: true
