language: minimal
services:
  - docker
before_install:
- cd ./blog
script: make build
deploy:
  provider: script
  script: make deploy
  on:
    branch: master
    condition: $TRAVIS_PULL_REQUEST == "false"
  skip_cleanup: true
